//CIBIS
public class CibisCandIrregularRequestEventWrap {
    
    public String entity;   //candidate
    public String subEntity;    //
    public String transactionId;    //c407e88b-fe1c-403c-bf3b-c18147722a93
    public String operation;    //GET
    public String USMLEId;  //53256350
    public String field;    //TranscriptEvaluationInfo
    /*public static CibisCandIrregularRequestEventWrap parse(String json){
        return (CibisCandIrregularRequestEventWrap) System.JSON.deserialize(json, CibisCandIrregularRequestEventWrap.class);
    }*/
}