public with sharing class CibisDupCheckExamRequest{
   /* public String entity{get;set;}
	public String subEntity{get;set;}
	public String transactionId{get;set;}
	public String operation{get;set;}
	public String USMLEId{get;set;}
	public String field{get;set;} */
    
    public String entity;
	public String subEntity;
	public String transactionId;
	public String operation;
	public String USMLEId;
	public String field;
}