//Handler class to prevent CaseTrigger recursion
public class RecursiveTriggerHandler{
     public Static Boolean isFirstTime = true;
     public static Boolean isFirstTimeRelatedTranscript=TRUE;
     public Static Boolean isFirstTimeBeforeUpdate = true;
     public Static Boolean isFirstTimeCV = true;
     public Static Boolean isFirstTimeCibis = True;
     public Static Boolean isFirstTimeCreVer = true;
     public Static Boolean isFirstTimeInvestigation = true;
}