public with sharing class WDOMSAccURLResponse {
    
        public class Payload {
            public String entity;	
            public String subEntity;	
            public String operation;
            public cls_payload payload;	
        }
        public class cls_payload{
            public String url;	
            public String sfurlId;	
            public String sfschoolId;	
            public String language; 
        }
}