public with sharing class WDOMSAccountResponse {

	public class Payload{
		public String entity;
		public String subEntity;
		public String operation;
		public cls_payload payload;			
	}
	
	public class cls_payload {
		public String sfSchoolId;	
		public String medSchoolCode;
		public String schoolName;
		public string countryCode;
		public String deletedFlag;
		public String address1;
		public String address2;
		public String address3;
		public String address4;
		public String city;
		public String stateCode;
		public String zip;
		public String universityName;
		public String schoolUrl;
		public String imedComments;
		public String startYear;
		public String curriculumDuration;
		public String entranceExamFlag;
		public String totalEnrollment;
		public String schoolId;	
		public String schoolTypeCode;
		public String currentlyOperationalFlag;
		public String yearClosed;	
		public String wdmsVisibleFlag;
		public String mdtFseTypeCode;
		public String currOtherCountryFlag;
		public String tuitionPaidPortion;
		public String clinicalFacilitiesFlag;
		public String mdtProgramGenderTypeCode;
		public String currClinicalPct;
		public String wdmsAddedDate;		
		public String ISOSubdivisionCode;
		public String xrefMSCode;	
		public String nameLanguageCode;
		public String notes;	
		public String extranceExamFlag;
		public String curriculumComments;
		public String latitude;
		public String longitude;				
		
	}    
}